version: '3'
services:
  golang-labs:
    container_name: golang-labs
    image: seandou/alpine-go:v1.9
    build: .
    # restart: always
    ports:
      - "8080"
    volumes:
      - ./etc/bashrc:/home/www/.bashrc

      - .gopath:/go
      - .:/home/www/go/src/github.com/seandou/golang-labs
    tty: true
    command: /bin/bash
    working_dir: /home/www/go/src/github.com/seandou/golang-labs
    networks:
      devops:
        ipv4_address: 172.31.0.3
    external_links:
      - mysql:mysql
      - redis:redis

networks:
  devops:
    external: true
